### ISSUE TITLE
Configuration screen not reactive on firmware 3.65.0

### ISSUE THREAD

**Issue by FrankHJCuypers** [FrankHJCuypers/Gaai#17]
**Describe the bug**
Reported by @jplandrain.

The Configuration screen only shows 0 values.
Editing values is possible, but the configuration screen does not show the new values but only the 0 values.

**To Reproduce**
1. Add the device based on PN and SN
2. Connect to the device and scroll to the Configuration screen
3. The screen only shows values 0 or Unknown
4. Edit a value and press OK.
5. The screen still only shows values 0 or Unknown

**Expected behavior**
At least the *Default mode* in the Configuration screen should be different from Unknown.
After editing a value and pressing OK, the new value should be reflected in the Configuration screen.

**Screenshots**
Example of incorrect Configuration screen:
![image](https://github.com/user-attachments/assets/6a537488-18fb-44c5-8cae-6cfdddff32f1)

**Android phone (please complete the following information):**
 - Device: [e.g. Google Pixel 6 Pro (see Settings->About phone->Model)]
 - Android version : [e.g. 14  (see Settings->About phone->Android version)]

**Nexxtender Home (As reported by *Gaai* or apps like *LightBlue*, *nRF Connect* or *BLE Analyzer* in the *Device Information* section):**
 - Firmware Revision: 3.65.0
 - Hardware Revision: A2

**Gaai version: Gaai-v1(0.0.1-103-ge7a5591-dev_FCU)-debug.apk**
From https://github.com/FrankHJCuypers/Gaai/releases/tag/v0.0.1-experimental

**Additional context**
None

**Comment by FrankHJCuypers** [comment]
Nexxtender Home has 3 different message types for reading/writing the configuration:
1. **1_0**  in use before firmware version 1.1.0
2. **1_1** in use from firmware version 1.1.1
3. **CBOR** in use from firmware version 3.50

*Gaai* uses the message type that corresponds with the firmware version.
Only version 1_1 was tested by me; it corresponds with the firmware version 2.53.2 of my Nexxtender Home. The other versions I can not fully test.

Root cause is that in the `when`  block that handles all notifications from the Nexxtender Home, the CONFIG_STATUS_POPPED_CBOR (value 0x5006) was forgotten. So these messages where ignored by *Gaai*.

**Comment by jplandrain** [comment]
Nexxtender Home
Firmware revision : 3.65.0
Hardware revision : A2

**Comment by FrankHJCuypers** [comment]
Root cause is that in the when block that handles all notifications from the Nexxtender Home, the CONFIG_STATUS_POPPED_CBOR (value 0x5006) was forgotten. So these messages where ignored by Gaai.
